Handle merge conflict

diff --git a/.github/workflows/automerger.yml b/.github/workflows/automerger.yml
--- a/.github/workflows/automerger.yml
+++ b/.github/workflows/automerger.yml
@@ -11,25 +11,27 @@ jobs:
     timeout-minutes: 5
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
     - name: Set Git config
       run: |
           git config --local user.email "actions@github.com"
           git config --local user.name "Github Actions"
           git fetch --unshallow
-    # TODO handling conflict / skip etc
     - name: Merge main back to dev
+      continue-on-error: true
       run: |
           git checkout dev
           git pull
-          git merge main --ff -m "Auto-update dev from main" && git push || echo "Unable to automatically merge dev"
+          git merge main --ff -m "Auto-update dev from main" && git push || (echo "Unable to automatically merge dev" && git merge --abort && exit 1)
     - name: Merge main back to dev-wrapper
+      continue-on-error: true
       run: |
           git checkout dev-wrapper
           git pull
-          git merge main --ff -m "Auto-update dev-wrapper from main" && git push || echo "Unable to automatically merge dev-wrapper"
+          git merge main --ff -m "Auto-update dev-wrapper from main" && git push || (echo "Unable to automatically merge dev-wrapper" && git merge --abort && exit 1)
     - name: Merge main back to dev-images
+      continue-on-error: true
       run: |
           git checkout dev-images
           git pull
-          git merge main --ff -m "Auto-update dev-images from main" && git push || echo "Unable to automatically merge dev-images"
+          git merge main --ff -m "Auto-update dev-images from main" && git push || (echo "Unable to automatically merge dev-images" && git merge --abort && exit 1)
